// Author: Gabriela Martinez
export const moviesSeeder = [
  {
    id: 1,
    title: 'The Devil Wears Prada',
    description:
      'A smart, stylish comedy-drama about a young woman who lands a job as an assistant to one of the most powerful fashion magazine editors in New York City.',
    cast: 'Meryl Streep, Anne Hathaway, Emily Blunt',
    director: 'David Frankel',
    releaseDate: new Date('2006-06-30'),
    genre: 'Drama',
    durationMin: 109,
    country: 'United States',
    language: 'English',
    actressId: 1,
    image: 'https://assets.mubicdn.net/images/film/3658/image-w1280.jpg?1745489583',
  },
  {
    id: 2,
    title: "Sophie's Choice",
    description:
      'A haunting and powerful story of a Polish immigrant living in Brooklyn who is torn between two men and haunted by a dark secret from her past in Nazi-occupied Poland.',
    cast: 'Meryl Streep, Kevin Kline, Peter MacNicol',
    director: 'Alan J. Pakula',
    releaseDate: new Date('1982-12-08'),
    genre: 'Drama',
    durationMin: 150,
    country: 'United States',
    language: 'English',
    actressId: 1,
    image: 'https://spoilertown.com/wp-content/uploads/2025/09/sophies-choice-1982.webp',
  },
  {
    id: 3,
    title: 'Blue Jasmine',
    description:
      'A faded New York socialite attempts to reinvent herself after her life falls apart, moving in with her working-class sister in San Francisco.',
    cast: 'Cate Blanchett, Alec Baldwin, Sally Hawkins',
    director: 'Woody Allen',
    releaseDate: new Date('2013-07-26'),
    genre: 'Drama',
    durationMin: 98,
    country: 'United States',
    language: 'English',
    actressId: 2,
    image: 'https://is1-ssl.mzstatic.com/image/thumb/hfNu7B-G798kCZAK5E_9dQ/1200x675.jpg',
  },
  {
    id: 4,
    title: 'Carol',
    description:
      'An aspiring photographer develops an intimate relationship with an older woman going through a difficult divorce in 1950s New York.',
    cast: 'Cate Blanchett, Rooney Mara, Kyle Chandler',
    director: 'Todd Haynes',
    releaseDate: new Date('2015-11-20'),
    genre: 'Romance',
    durationMin: 118,
    country: 'United Kingdom',
    language: 'English',
    actressId: 2,
    image: 'https://variety.com/wp-content/uploads/2015/05/carol-cannes-film-festival-3.jpg?w=1000&h=563&crop=1',
  },
  {
    id: 5,
    title: 'Volver',
    description:
      'A dark comedy in which a mother returns from the dead to fix the problems she left behind for her two daughters.',
    cast: 'Penélope Cruz, Carmen Maura, Lola Dueñas',
    director: 'Pedro Almodóvar',
    releaseDate: new Date('2006-03-17'),
    genre: 'Comedy',
    durationMin: 121,
    country: 'Spain',
    language: 'Spanish',
    actressId: 3,
    image: 'https://kviff.tv/media/_cache/film_detail_cover/films/2024/09/20/Volver_02.jpg',
  },
  {
    id: 6,
    title: 'Parallel Mothers',
    description:
      'Two mothers, one middle-aged and one a teenager, share a hospital room where they give birth at the same time, sparking a friendship with profound consequences.',
    cast: 'Penélope Cruz, Milena Smit, Rossy de Palma',
    director: 'Pedro Almodóvar',
    releaseDate: new Date('2021-09-01'),
    genre: 'Drama',
    durationMin: 123,
    country: 'Spain',
    language: 'Spanish',
    actressId: 3,
    image: 'https://variety.com/wp-content/uploads/2021/05/parallel-mothers-1-e1629742836709.jpg',
  },
  {
    id: 7,
    title: 'Black Swan',
    description:
      'A committed dancer wins the lead role in a production of Swan Lake only to find herself struggling to maintain her sanity as she personifies the evil black swan.',
    cast: 'Natalie Portman, Mila Kunis, Vincent Cassel',
    director: 'Darren Aronofsky',
    releaseDate: new Date('2010-12-17'),
    genre: 'Thriller',
    durationMin: 108,
    country: 'United States',
    language: 'English',
    actressId: 4,
    image: 'https://cinemotic.com/wp-content/uploads/2021/09/black-swan-movie-shot.jpg',
  },
  {
    id: 8,
    title: 'Jackie',
    description:
      "Following the assassination of President John F. Kennedy, First Lady Jacqueline Kennedy fights through grief and trauma to regain her faith, console her children, and define her husband's historic legacy.",
    cast: 'Natalie Portman, Peter Sarsgaard, Greta Gerwig',
    director: 'Pablo Larraín',
    releaseDate: new Date('2016-09-07'),
    genre: 'Biography',
    durationMin: 100,
    country: 'Chile',
    language: 'English',
    actressId: 4,
    image: 'https://m.media-amazon.com/images/S/pv-target-images/60f35eebba2695ae720f8d422abbf3aa4800a0b55724ee4f1db552801c3dcb81._SX1080_FMpng_.png',
  },
  {
    id: 9,
    title: 'Fences',
    description:
      'A working-class African-American father struggles with race relations in the United States while trying to raise his family in the 1950s and trying to pursue a career in baseball.',
    cast: 'Viola Davis, Denzel Washington, Stephen Henderson',
    director: 'Denzel Washington',
    releaseDate: new Date('2016-12-25'),
    genre: 'Drama',
    durationMin: 139,
    country: 'United States',
    language: 'English',
    actressId: 5,
    image: 'https://m.media-amazon.com/images/M/MV5BMjMwMzgwODc0MV5BMl5BanBnXkFtZTgwOTY3Njg4MDI@._V1_.jpg',
  },
  {
    id: 10,
    title: 'La Vie en Rose',
    description:
      'The story of the iconic French singer Édith Piaf, from her childhood in Paris through her rise to international fame and her troubled personal life.',
    cast: 'Marion Cotillard, Sylvie Testud, Pascal Greggory',
    director: 'Olivier Dahan',
    releaseDate: new Date('2007-02-14'),
    genre: 'Biography',
    durationMin: 140,
    country: 'France',
    language: 'French',
    actressId: 6,
    image: 'https://m.media-amazon.com/images/S/pv-target-images/c455681da5714774deab81a84623e2b804053ede2ff3ea80e32b32c132859db1.jpg',
  },
  {
    id: 11,
    title: 'Two Days, One Night',
    description:
      'A young Belgian woman spends a weekend trying to convince her colleagues to give up their bonuses so that she can keep her job.',
    cast: 'Marion Cotillard, Fabrizio Rongione, Pili Groyne',
    director: 'Jean-Pierre Dardenne, Luc Dardenne',
    releaseDate: new Date('2014-05-20'),
    genre: 'Drama',
    durationMin: 95,
    country: 'Belgium',
    language: 'French',
    actressId: 6,
    image: 'https://i.guim.co.uk/img/static/sys-images/Guardian/Pix/pictures/2014/8/21/1408620532995/-Mesmerising--Marion-Coti-011.jpg?width=465&dpr=1&s=none&crop=none',
  },
  {
    id: 12,
    title: 'Lady Bird',
    description:
      'A teenager in Sacramento navigates the bittersweet journey of growing up, fighting with her mother, falling in love, and ultimately discovering her own identity.',
    cast: 'Saoirse Ronan, Laurie Metcalf, Tracy Letts',
    director: 'Greta Gerwig',
    releaseDate: new Date('2017-09-01'),
    genre: 'Comedy',
    durationMin: 94,
    country: 'United States',
    language: 'English',
    actressId: 7,
    image: 'https://occ-0-8407-2218.1.nflxso.net/dnm/api/v6/6AYY37jfdO6hpXcMjf9Yu5cnmO0/AAAABdWOpLrYW2MebXJ6CILWdN3hFw9QA1Bte2vwoXcKIG3k8BvlbQeBVOuj82z_TMO_YEqyb8IatmVarROdQZesKxWRYGZ_oADVdpdP.jpg?r=401',
  },
  {
    id: 13,
    title: 'Little Women',
    description:
      'Jo March reflects back and recounts to her sisters how they all came of age during the Civil War era, navigating love, ambition, identity, and independence.',
    cast: 'Saoirse Ronan, Emma Watson, Florence Pugh',
    director: 'Greta Gerwig',
    releaseDate: new Date('2019-12-25'),
    genre: 'Romance',
    durationMin: 135,
    country: 'United States',
    language: 'English',
    actressId: 7,
    image: 'https://m.media-amazon.com/images/S/pv-target-images/4b236c1551076741854c8de6707519c3ec8e963b0bcd1002803797856328190f._SX1080_FMjpg_.jpg',
  },
  {
    id: 14,
    title: 'Crouching Tiger, Hidden Dragon',
    description:
      'A young Chinese warrior steals a sword from a famed swordsman and then escapes into a world of romantic adventure with a mysterious man in the Gobi Desert.',
    cast: 'Zhang Ziyi, Michelle Yeoh, Chow Yun-fat',
    director: 'Ang Lee',
    releaseDate: new Date('2000-07-06'),
    genre: 'Action',
    durationMin: 120,
    country: 'China',
    language: 'Mandarin',
    actressId: 8,
    image: 'https://i.ytimg.com/vi/a3sQIjbrMQw/maxresdefault.jpg',
  },
  {
    id: 15,
    title: 'House of Flying Daggers',
    description:
      'A romantic police captain breaks a beautiful member of a rebel group out of prison to help her rejoin her fellows, and together they begin a journey through ancient China.',
    cast: 'Zhang Ziyi, Takeshi Kaneshiro, Andy Lau',
    director: 'Zhang Yimou',
    releaseDate: new Date('2004-07-16'),
    genre: 'Action',
    durationMin: 119,
    country: 'China',
    language: 'Mandarin',
    actressId: 8,
    image: 'https://www.screenslate.com/sites/default/files/2025-04/House-of-flying-Daggers.jpg',
  },
];
